name: "make github release description"
description: "make github release description"

inputs:
  version:
    description: "jira version"
    required: true
  projectKey:
    description: "jira project"
    required: true
  jira_token:
    description: "jira auth token"
    required: true
  jira_domain:
    description: "jira domain"
    required: true

outputs:
  content:
    description: "release description"

runs:
  using: "node16"
  main: "dist/index.js"
